name: Update README Table of Contents

on:
  push:
    branches: [ main ]
    paths:
      - "README.md"
  pull_request:
    paths:
      - "README.md"

jobs:
  update-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install doctoc
        run: npm install -g doctoc

      - name: Generate TOC
        run: doctoc README.md --title '## ðŸ“š Table of Contents'

      - name: Commit changes if TOC updated
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add README.md
            git commit -m "docs: auto-update Table of Contents"
            git push
          else
            echo "âœ… TOC is up to date."
          fi
